# Use the official Golang image as the base image
FROM golang:1.20 as builder

# Set the working directory inside the container
WORKDIR /app

# Copy go.mod and go.sum files to the workspace
COPY go.mod go.sum ./

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download

# Copy the source code into the container
COPY . .

# Build the Go application
RUN go build -o main .

# Use a minimal image as the base image for the final container
FROM alpine:latest

# Set the working directory inside the container
WORKDIR /root/

# Copy the binary from the builder container
COPY --from=builder /app/main .

# Copy .env file
COPY .env .

# Install PostgreSQL client for database interaction
RUN apk add --no-cache postgresql-client

# Command to run the executable
CMD ["./main"]
